version: '3.8'

services:
  safenotes:
    build: ./safenotes  # Asume que Dockerfile está dentro de safenotes/
    image: safenotes:latest  # Add this line
    ports:
      - "3000:3000"
    networks:
      - devsecops-net
    environment:
      - HTTP_PROXY=http://zap:8082
    restart: unless-stopped

  dependency-check:
    image: owasp/dependency-check
    volumes:
      - ./safenotes:/src
      - ./reports:/report
    command: ["--project", "safenotes", "--scan", "/src", "--format", "ALL", "--out", "/report", "--disableAssembly"]
    networks:
      - devsecops-net

  trivy:
    image: aquasec/trivy:latest
    ports:
      - "8081:8080"
    volumes:
      - trivy_cache:/root/.cache/trivy
      - ./reports:/report  # Mount local reports directory
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TRIVY_CACHE_DIR=/root/.cache/trivy
      - TRIVY_SKIP_DB_UPDATE=true
    networks:
      - devsecops-net
    restart: no
    depends_on:
      - safenotes
    command: [
      "image",
      "--scanners", "vuln",
      "--severity", "CRITICAL,HIGH,MEDIUM",
      "--ignore-unfixed",
      "--format", "template",
      "--template", "@/contrib/html.tpl",  # Built-in HTML template
      "--output", "/report/trivy-report.html",
      "safenotes:latest"
    ]

  zap: #TODO: Arreglar API ZAP (curl retorna 52 empty response)
    image: zaproxy/zap-weekly:latest
    ports:
      - "8082:8082"  # Proxy + UI port interno 8082
      - "8090:8090"  # API port interno 8090
    environment:
      - ZAP_AUTOSTART=true
      - ZAP_API_KEY=a8df14b272a794e4d1d178b1ebba1bbf
      - ZAP_PROXY_ALLOWREMOTE=true
      - ZAP_PROXY_ALLOWLOCALHOST=true
    command: >
      zap.sh -daemon
      -host 0.0.0.0
      -port 8082
      -config proxy.ip=0.0.0.0
      -config proxy.port=8082
      -config proxy.behindnat=true
      -config network.connection.timeoutInSecs=60
      -config api.enabled=true
      -config api.key=$$ZAP_API_KEY
      -config api.port=8090
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
    networks:
      - devsecops-net
    depends_on:
      - safenotes

volumes:
  trivy_cache:
  zap_data:

networks:
  devsecops-net:
    driver: bridge
